### ISSUE TITLE
お問い合わせ管理システム：追加功能二 / 管理者指定担当者時

### ISSUE THREAD

**Issue by JohnsonChung** [JohnsonChung/J-Quest#18]
現在管理者指定担当者時，已經有通知Email
在mail裡面追加下面資料

追加的資料來源：
![image](https://cloud.githubusercontent.com/assets/4928770/10973153/17ac7eae-8417-11e5-828c-5d6e3b276ea0.png)

追加後的 Email ；
![image](https://cloud.githubusercontent.com/assets/4928770/10973157/1bcaec64-8417-11e5-887f-7c50d1dd21bd.png)

並且在下面的討論區塊發出一個訊息，
紀錄做出這個"指定動作"的人。

**Comment by JohnsonChung** [comment]
日付：(動作時間)
カテゴリ：(類別)
担当者：(被指定的擔當者名)
メッセージ：(內容)

佐藤 (管理者名)

**Comment by touhonoob** [comment]
- [x] 更新email
- [x] 發comment

**Comment by touhonoob** [comment]
https://github.com/touhonoob/jquest-contact/commit/5b8a3c844e9ed17ae7060187b0091f1f1385e5a1
