### ISSUE TITLE
お問い合わせ管理システム：最後兩點修正

### ISSUE THREAD

**Issue by JohnsonChung** [JohnsonChung/J-Quest#19]
## 上傳報告發的E-mail

**標題：**

> お問合せNo.24 - 対応完了。担当者：：{{Account Name}}

**內文：**
只需要有直連到該筆お問い合わせ的anchor就好
- [x] 完成
## 指定擔當者時的E-mail內容修正 (全黑字)

> **日付：** 2015-11-06 01:51:33 
> **カテゴリ：** 問合せ 
> **担当者：** 佐藤
> **メッセージ：**
> 
> **責任者：**鈴木
- [x] 完成
## 完成後等suzuki確認後就可以全部轉到新系統
- [x] 完成

**Comment by touhonoob** [comment]
> 対応完了。担当：{{Account Name}}

用上傳者的名稱？

**Comment by JohnsonChung** [comment]
改成這樣

> お問合せNo.24 - 対応完了。担当者：{{Account Name}}

**Comment by JohnsonChung** [comment]
最後一個

> お問合せNo.24 - 対応完了。担当者：{{擔當者名}}
